# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smart_environment.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17smart_environment.proto\x12\x11smart_environment\"&\n\x14StatusArCondicionado\x12\x0e\n\x06ligado\x18\x01 \x01(\x08\"\x07\n\x05Vazio2\xe3\x01\n\x0e\x41rCondicionado\x12=\n\x05Ligar\x12\x18.smart_environment.Vazio\x1a\x18.smart_environment.Vazio\"\x00\x12@\n\x08\x44\x65sligar\x12\x18.smart_environment.Vazio\x1a\x18.smart_environment.Vazio\"\x00\x12P\n\tgetStatus\x12\x18.smart_environment.Vazio\x1a\'.smart_environment.StatusArCondicionado\"\x00\x32\x9a\x01\n\x17SistemaControleIncendio\x12=\n\x05Ligar\x12\x18.smart_environment.Vazio\x1a\x18.smart_environment.Vazio\"\x00\x12@\n\x08\x44\x65sligar\x12\x18.smart_environment.Vazio\x1a\x18.smart_environment.Vazio\"\x00\x32\x8a\x01\n\x07Lampada\x12=\n\x05Ligar\x12\x18.smart_environment.Vazio\x1a\x18.smart_environment.Vazio\"\x00\x12@\n\x08\x44\x65sligar\x12\x18.smart_environment.Vazio\x1a\x18.smart_environment.Vazio\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'smart_environment_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STATUSARCONDICIONADO']._serialized_start=46
  _globals['_STATUSARCONDICIONADO']._serialized_end=84
  _globals['_VAZIO']._serialized_start=86
  _globals['_VAZIO']._serialized_end=93
  _globals['_ARCONDICIONADO']._serialized_start=96
  _globals['_ARCONDICIONADO']._serialized_end=323
  _globals['_SISTEMACONTROLEINCENDIO']._serialized_start=326
  _globals['_SISTEMACONTROLEINCENDIO']._serialized_end=480
  _globals['_LAMPADA']._serialized_start=483
  _globals['_LAMPADA']._serialized_end=621
# @@protoc_insertion_point(module_scope)
